import argparse
import pandas as pd
import numpy as np
import os
import joblib
from src.features import FeatureGenerator
from src.model import EntityResolutionModel
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import fbeta_score, precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')

def load_ground_truth(gt_path):
    """
    Loads train_ground_truth.tsv and returns a dictionary mapping
    source1_entity_id -> set of matched candidate_entity_ids
    """
    gt_df = pd.read_csv(gt_path, sep='\t')
    if 'source1_entity_id' not in gt_df.columns or 'matched_entity_ids' not in gt_df.columns:
        raise ValueError("Ground truth file missing required columns.")
        
    gt_map = {}
    for _, row in gt_df.iterrows():
        s1_id = row['source1_entity_id']
        matches_str = str(row['matched_entity_ids'])
        if matches_str and matches_str != 'nan':
            gt_map[s1_id] = set([x.strip() for x in matches_str.split(',') if x.strip()])
        else:
            gt_map[s1_id] = set()
    return gt_map

def assign_labels(pairs_df, gt_map):
    """
    Assigns labels based on the ground truth mapping.
    label = 1 if candidate_entity_id in matched_entity_ids else 0
    """
    def check_match(row):
        s1 = row['source1_entity_id']
        cand = row['candidate_entity_id']
        if s1 not in gt_map:
            # If the S1 ID doesn't exist in ground truth at all, it's invalid.
            raise ValueError(f"Invalid entity ID {s1} not found in ground truth.")
        return 1 if cand in gt_map[s1] else 0
        
    pairs_df['label'] = pairs_df.apply(check_match, axis=1)
    return pairs_df

def log_experiment(results_path, result_dict):
    """
    Logs the experiment result to the specified CSV path.
    """
    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    df = pd.DataFrame([result_dict])
    if os.path.exists(results_path):
        df.to_csv(results_path, mode='a', header=False, index=False)
    else:
        df.to_csv(results_path, index=False)

def main():
    parser = argparse.ArgumentParser(description="Train ML models for Entity Resolution")
    parser.add_argument("--candidate_pairs", type=str, default="output/candidate_pairs.tsv", 
                        help="Path to candidate pairs TSV file generated by blocking.")
    parser.add_argument("--s1_data", type=str, default="dataset/train/train_source1.tsv")
    parser.add_argument("--s2_data", type=str, default="dataset/train/train_source2.tsv")
    parser.add_argument("--s3_data", type=str, default="dataset/train/train_source3.tsv")
    parser.add_argument("--gt_data", type=str, default="dataset/train/train_ground_truth.tsv")
    parser.add_argument("--out_dir", type=str, default="models/")
    parser.add_argument("--results_log", type=str, default="experiments/results.csv")
    parser.add_argument("--dev", action="store_true", help="Run in development mode with a small synthetic candidate sample.")
    parser.add_argument("--seed", type=int, default=42)
    
    args = parser.parse_args()
    
    if not args.candidate_pairs and not args.dev:
        print("Error: Candidate pairs file not provided.")
        print("MODEL CODE READY — WAITING FOR MEMBER 1 CANDIDATE PAIRS")
        return
        
    if args.candidate_pairs and not os.path.exists(args.candidate_pairs) and not args.dev:
        print(f"Error: Required candidate file '{args.candidate_pairs}' is unavailable.")
        print("MODEL CODE READY — WAITING FOR MEMBER 1 CANDIDATE PAIRS")
        return

    print("Loading datasets...")
    df_s1 = pd.read_csv(args.s1_data, sep='\t', dtype=str)
    df_s2 = pd.read_csv(args.s2_data, sep='\t', dtype=str)
    df_s3 = pd.read_csv(args.s3_data, sep='\t', dtype=str)
    df_cand_full = pd.concat([df_s2, df_s3]).reset_index(drop=True)
    
    gt_map = load_ground_truth(args.gt_data)
    
    if args.dev:
        print("Running in DEV mode with small synthetic sample...")
        # Create a tiny subset of fake pairs that include positive and negative examples
        sample_s1 = df_s1.head(20)['entity_id'].tolist()
        pairs = []
        for s1 in sample_s1:
            if s1 in gt_map and len(gt_map[s1]) > 0:
                # Add positive pair
                pairs.append({'source1_entity_id': s1, 'candidate_entity_id': list(gt_map[s1])[0]})
                # Add negative pair
                pairs.append({'source1_entity_id': s1, 'candidate_entity_id': df_s2.iloc[0]['entity_id']})
        
        pairs_df = pd.DataFrame(pairs)
    else:
        print(f"Loading candidate pairs from {args.candidate_pairs}...")
        pairs_df = pd.read_csv(args.candidate_pairs, sep='\t')
        
    if len(pairs_df) == 0:
        raise ValueError("Empty candidate data.")
        
    # Check duplicates
    if pairs_df.duplicated(subset=['source1_entity_id', 'candidate_entity_id']).any():
        raise ValueError("Duplicate candidate pairs detected.")
        
    # Assign labels
    pairs_df = assign_labels(pairs_df, gt_map)
    
    print(f"Class distribution: 0={sum(pairs_df['label'] == 0)}, 1={sum(pairs_df['label'] == 1)}")
    
    if len(pairs_df['label'].unique()) <= 1:
        raise ValueError("Only-one-class training data encountered.")
    
    print("Generating features...")
    fg = FeatureGenerator()
    
    # Split BEFORE feature generation fitting to prevent data leakage in TF-IDF
    # Group by source1_entity_id
    gss = GroupShuffleSplit(n_splits=1, train_size=0.8, random_state=args.seed)
    train_idx, val_idx = next(gss.split(pairs_df, groups=pairs_df['source1_entity_id']))
    
    if len(val_idx) == 0 or len(train_idx) == 0:
        raise ValueError("Empty train or validation split.")
        
    train_pairs = pairs_df.iloc[train_idx].reset_index(drop=True)
    val_pairs = pairs_df.iloc[val_idx].reset_index(drop=True)
    
    # Check overlap
    train_s1 = set(train_pairs['source1_entity_id'].unique())
    val_s1 = set(val_pairs['source1_entity_id'].unique())
    if len(train_s1.intersection(val_s1)) > 0:
        raise ValueError("Group-aware split failed! S1 entities overlap between train and validation.")
        
    print(f"Train pairs: {len(train_pairs)}, Val pairs: {len(val_pairs)}")
    
    # Generate features (Fit on train, transform on both)
    # The FG uses df_s1 and df_cand_full to look up actual strings
    # But it only fits TF-IDF on the entities present in train_pairs
    train_s1_df = df_s1[df_s1['entity_id'].isin(train_pairs['source1_entity_id'])]
    train_cand_df = df_cand_full[df_cand_full['entity_id'].isin(train_pairs['candidate_entity_id'])]
    
    fg.fit(train_s1_df, train_cand_df, train_pairs)
    
    train_features = fg.transform(df_s1, df_cand_full, train_pairs)
    val_features = fg.transform(df_s1, df_cand_full, val_pairs)
    
    # Check columns
    feature_cols = fg.feature_names
    if list(train_features.columns) != ['source1_entity_id', 'candidate_entity_id'] + feature_cols:
        raise ValueError("Mismatched feature columns generated.")
        
    X_train = train_features[feature_cols]
    y_train = train_pairs['label']
    
    X_val = val_features[feature_cols]
    y_val = val_pairs['label']
    
    print("Training models...")
    os.makedirs(args.out_dir, exist_ok=True)
    
    # Save the feature configuration
    fg.save(os.path.join(args.out_dir, 'feature_generator.joblib'))
    
    models = ['logistic_regression', 'random_forest']
    
    for model_type in models:
        print(f"Training {model_type}...")
        model = EntityResolutionModel(model_type=model_type, random_state=args.seed)
        model.fit(X_train, y_train)
        model.save(os.path.join(args.out_dir, f'{model_type}.joblib'))
        
        # Validation
        val_preds = model.predict(X_val)
        val_probs = model.predict_proba(X_val)
        
        precision = precision_score(y_val, val_preds, zero_division=0)
        recall = recall_score(y_val, val_preds, zero_division=0)
        f0_5 = fbeta_score(y_val, val_preds, beta=0.5, zero_division=0)
        
        # Save experiment log
        result_dict = {
            'model': model_type,
            'random_seed': args.seed,
            'train_entities': len(train_s1),
            'validation_entities': len(val_s1),
            'train_pairs': len(train_pairs),
            'validation_pairs': len(val_pairs),
            'positive_pairs': int(y_train.sum() + y_val.sum()),
            'negative_pairs': int(len(pairs_df) - (y_train.sum() + y_val.sum())),
            'feature_count': len(feature_cols),
            'validation_precision': precision,
            'validation_recall': recall,
            'validation_f0_5': f0_5
        }
        
        log_experiment(args.results_log, result_dict)
        print(f"Validation F0.5: {f0_5:.4f}")
        
        # Save validation predictions for evaluate.py
        val_out = val_pairs.copy()
        val_out['score'] = val_probs[:, 1]
        val_out.to_csv(os.path.join(args.out_dir, f'val_predictions_{model_type}.tsv'), sep='\t', index=False)

    print("Model training pipeline completed successfully.")

if __name__ == '__main__':
    main()
